name: Android Release APK

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release-apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android platforms and build tools
        run: |
          sdkmanager "platforms;android-34" "build-tools;34.0.0"

      - name: Gradle cache
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: app

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/app/build/outputs/apk/debug/*.apk
          generate_release_notes: true
