name: Android CI (Build on Push)

on:
  push:
    branches: [develop, main]
    paths:
      - "app/**"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-upload-apk:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Gradle cache
        uses: gradle/gradle-build-action@v3
        with:
          build-root-directory: app

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Prepare named APK (branch + short SHA)
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          DEST="app/build/outputs/apk/debug/app-debug-${{ github.ref_name }}-$SHORT_SHA.apk"
          cp app/build/outputs/apk/debug/*.apk "$DEST"

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk-${{ github.ref_name }}-${{ env.SHORT_SHA }}
          path: app/build/outputs/apk/debug/app-debug-${{ github.ref_name }}-${{ env.SHORT_SHA }}.apk
          if-no-files-found: error
